/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.pedidos;

import DAO.DAOUsuario;
import DAO.FormaPagamentoDAO;
import DAO.PedidoDAO;
import Model.ModelFormaPagamento;
import Model.ModelItensPedido;
import Model.ModelPedido;
import Model.ModelUsuario;
import java.awt.Color;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.prompt.PromptSupport;


/**
 *
 * @author Vaio
 */
public class JDCadastrarPedido extends javax.swing.JDialog 
{
    ArrayList<ModelFormaPagamento> formaPagamentos;
    /**
     * Creates new form jdCadastrarPedido
     */
    public JDCadastrarPedido(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Cadastrar Pedido");
        this.setLocationRelativeTo(null);
    }
    
    
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBSalvar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JTFUsuarioID = new javax.swing.JTextField();
        JTFFormaPagamento = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(270, 318));
        setPreferredSize(new java.awt.Dimension(285, 370));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JBSalvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JBSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/check.png"))); // NOI18N
        JBSalvar.setText("Salvar");
        JBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(JBSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 295, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/clear.png"))); // NOI18N
        jButton2.setText("Limpar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 295, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Forma do pagamento:");
        jLabel5.setPreferredSize(new java.awt.Dimension(44, 20));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 73, 242, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Usuário id:");
        jLabel6.setPreferredSize(new java.awt.Dimension(44, 20));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 19, 242, -1));

        JTFUsuarioID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTFUsuarioIDFocusLost(evt);
            }
        });
        JTFUsuarioID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFUsuarioIDActionPerformed(evt);
            }
        });
        JTFUsuarioID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTFUsuarioIDKeyReleased(evt);
            }
        });
        getContentPane().add(JTFUsuarioID, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 45, 242, -1));

        JTFFormaPagamento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTFFormaPagamentoFocusLost(evt);
            }
        });
        JTFFormaPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFFormaPagamentoActionPerformed(evt);
            }
        });
        JTFFormaPagamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTFFormaPagamentoKeyReleased(evt);
            }
        });
        getContentPane().add(JTFFormaPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 95, 242, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSalvarActionPerformed
        
        ModelPedido pedido = new ModelPedido();
        
        try {
        
    // Obtendo os valores dos campos de texto.
    
    
    int usuarioId = Integer.parseInt(JTFUsuarioID.getText());
    int formaPagamentoId = Integer.parseInt(JTFFormaPagamento.getText());
    //int statusPedido = Integer.parseInt(JTFStatusPedido.getText());
    //double total = Double.parseDouble(JTFTotal.getText());

    // Tentando converter.
            //System.out.println("Forma PGTo ID " +formaPagamentoId );
    int usuario = DAOUsuario.getUsuarioId(usuarioId);
   

    // Verificando se as instâncias não são nulas.
    
    if (usuario != -1) {
        
        ModelUsuario usuario2 = new ModelUsuario();
        usuario2.setId(usuario);
        pedido.setUsuarioId(usuario2);
        System.out.println("usuario2 " + usuario2);
        ModelFormaPagamento formaPagamento = FormaPagamentoDAO.obterFormaPagamento(formaPagamentoId);
        System.out.println("FormaPgto: " + formaPagamento.getDescricao());
        pedido.setFormaPagamentoId(formaPagamento);
        //pedido.setStatusPagamento(statusPagamento); -- paga depois?
        //pedido.setStatusPedido(statusPedido);     -- inicia sempre o mesmo valor default
        //pedido.setTotal(total);       -- pega depois 
        
        DAO.PedidoDAO.salvar(pedido);
        //JOptionPane.showMessageDialog(this, "Salvo com Sucesso!");
        this.dispose();
        
        //Passar o pedido por aqui
        JDialogPedidoCardapio jdPedidoCardapio = new JDialogPedidoCardapio(null, true, Integer.parseInt(JTFUsuarioID.getText()));
        jdPedidoCardapio.setVisible(true);
      
    } else {
        JOptionPane.showMessageDialog(this, "Id do usuário ou forma de pagamento não encontrado.");
    }
    
    } catch (Exception CADASTRAR) {
        throw new RuntimeException(CADASTRAR);
    }
        
        
    }//GEN-LAST:event_JBSalvarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JTFFormaPagamento.setText(null);
        //JTFStatusPagamento.setText(null);
        //JTFStatusPedido.setText(null);
        //JTFTotal.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void JTFUsuarioIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFUsuarioIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFUsuarioIDActionPerformed

    private void JTFUsuarioIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFUsuarioIDKeyReleased
        // TODO add your handling code here:
        //verificacaoUsuarioId = validacao("\\d+", JTFFormaPagamento);
        //visibilidade();
    }//GEN-LAST:event_JTFUsuarioIDKeyReleased

    private void JTFUsuarioIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFUsuarioIDFocusLost
        // TODO add your handling code here:
        if(JTFUsuarioID.getText().isBlank())
        {
            return;
        }
        int idUsuario = Integer.parseInt(JTFUsuarioID.getText());
        System.out.println("idusuario " + idUsuario);
        
        try 
        {
            int pedidoPendente = PedidoDAO.checarPedidoPendente(idUsuario);
            
            if(pedidoPendente > 0)
            {
                int input = JOptionPane.showConfirmDialog(rootPane, "Cliente Possui Pedido Pendente, Deseja Recuperar?", "Pedido Pendente", JOptionPane.YES_NO_OPTION);
                
                if(input == 0)
                {
                    this.dispose();
                    JDialogPedidoCardapio jdPedidoCardapio = new JDialogPedidoCardapio(null, true, Integer.parseInt(JTFUsuarioID.getText()));
                    jdPedidoCardapio.setVisible(true);
                }
                else
                {
                    PedidoDAO.deletarPedidoPendente(idUsuario);
                }
            }
        } 
        catch (ClassNotFoundException ex) {
            Logger.getLogger(JDCadastrarPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JTFUsuarioIDFocusLost

    private void JTFFormaPagamentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFFormaPagamentoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFFormaPagamentoFocusLost

    private void JTFFormaPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFFormaPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFFormaPagamentoActionPerformed

    private void JTFFormaPagamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFFormaPagamentoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFFormaPagamentoKeyReleased
    
    private boolean verificacaoUsuarioId;
    private boolean verificacaoFormaPagamentoId;
    private boolean verificacaoStatusPagamento;
    private boolean verificacaoStatusPedido;
    private boolean verificacaoTotal;
    
    
    private void visibilidade(){
        if (verificacaoUsuarioId && verificacaoFormaPagamentoId && verificacaoStatusPagamento && verificacaoStatusPedido &&
            verificacaoTotal){
            JBSalvar.setEnabled(true);
        } else {
            JBSalvar.setEnabled(false);
        }
    }
    
    private boolean validacao(String letrinha, JTextField field){
        String texto = field.getText();
        
        if(texto.matches(letrinha)){
            field.setForeground(Color.blue);
            return true;
        } else {
            field.setForeground(Color.red);
            field.requestFocus();
            return false;
        }
    }
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDCadastrarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDCadastrarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDCadastrarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDCadastrarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDCadastrarPedido dialog = new JDCadastrarPedido(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBSalvar;
    private javax.swing.JTextField JTFFormaPagamento;
    private javax.swing.JTextField JTFUsuarioID;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
