/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.formapagamentos;

/**
 *
 * @author Aluno TDS
 */
public class jdMenuPagamento extends javax.swing.JDialog {

    /**
     * Creates new form jdMenuPagamento
     */
    public jdMenuPagamento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbPix = new javax.swing.JButton();
        jbDinheiro = new javax.swing.JButton();
        jbCartao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jbPix.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbPix.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pix.png"))); // NOI18N
        jbPix.setText("PIX");
        jbPix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPixActionPerformed(evt);
            }
        });

        jbDinheiro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbDinheiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dinheiro.png"))); // NOI18N
        jbDinheiro.setText(" Dinheiro");
        jbDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDinheiroActionPerformed(evt);
            }
        });

        jbCartao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbCartao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cartao.png"))); // NOI18N
        jbCartao.setText("Cartão");
        jbCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCartaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbCartao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbPix)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbDinheiro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbPix)
                    .addComponent(jbDinheiro)
                    .addComponent(jbCartao))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbPixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPixActionPerformed
        // TODO add your handling code here:
        jdCadastrarPix b = new jdCadastrarPix(null, true);
        b.setVisible(true);
    }//GEN-LAST:event_jbPixActionPerformed

    private void jbDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDinheiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbDinheiroActionPerformed

    private void jbCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCartaoActionPerformed
        // TODO add your handling code here:
        jdCadastrarCartao a = new jdCadastrarCartao(null, true);
        a.setVisible(true);
    }//GEN-LAST:event_jbCartaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdMenuPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdMenuPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdMenuPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdMenuPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdMenuPagamento dialog = new jdMenuPagamento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCartao;
    private javax.swing.JButton jbDinheiro;
    private javax.swing.JButton jbPix;
    // End of variables declaration//GEN-END:variables
}
