package view.produto;

import DAO.ProdutoDAO;
import Model.ProdutoModel;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableColumn;
import tablemodel.TableModelProduto;


public class JDialogGerenciarProduto extends javax.swing.JDialog 
{
    
    public JDialogGerenciarProduto(java.awt.Frame parent, boolean modal) 
    {
        super(parent, modal);
        initComponents();
        jTableProdutos.setModel(initTable());
        ajustarTamanhoTabela();
        this.setLocationRelativeTo(null);
    }
    
    private TableModelProduto initTable() 
    {
        ProdutoDAO produtoDAO = new ProdutoDAO();
        
        return new TableModelProduto(produtoDAO.consultar());
    }

    public void ajustarTamanhoTabela() //ver depois
    {
        jTableProdutos.setRowHeight(25);
        
        TableColumn colunaID = jTableProdutos.getColumnModel().getColumn(0);
        colunaID.setPreferredWidth(80);
        colunaID.setMaxWidth(100);
        
        TableColumn colunaPreco = jTableProdutos.getColumnModel().getColumn(5);
        colunaPreco.setPreferredWidth(80);
        colunaPreco.setMaxWidth(100);

        atualizarTamanhoTabela();
    }
    
    public void atualizarTamanhoTabela()
    {
        Dimension size = new Dimension(500, jTableProdutos.getRowCount() * jTableProdutos.getRowHeight());
        jTableProdutos.setPreferredScrollableViewportSize(size);
        jTableProdutos.setPreferredSize(size);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        jTableProdutos = new javax.swing.JTable();
        jButtonEditar = new javax.swing.JButton();
        jButtonDeletar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta");
        setMinimumSize(new java.awt.Dimension(1000, 680));
        setPreferredSize(new java.awt.Dimension(1000, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Consultar Produtos");
        jLabelTitulo.setMinimumSize(new java.awt.Dimension(1000, 680));
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 6, 400, -1));

        jScrollPane.setPreferredSize(new java.awt.Dimension(1000, 550));

        jTableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Categoria", "Foto", "Nome", "Descrição", "Preço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProdutos.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jTableProdutos.setPreferredSize(new java.awt.Dimension(800, 200));
        jTableProdutos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane.setViewportView(jTableProdutos);
        if (jTableProdutos.getColumnModel().getColumnCount() > 0) {
            jTableProdutos.getColumnModel().getColumn(0).setResizable(false);
            jTableProdutos.getColumnModel().getColumn(0).setPreferredWidth(25);
        }

        getContentPane().add(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 120, 950, 500));

        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/paper.png"))); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.setMaximumSize(new java.awt.Dimension(72, 25));
        jButtonEditar.setMinimumSize(new java.awt.Dimension(90, 25));
        jButtonEditar.setPreferredSize(new java.awt.Dimension(90, 25));
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 90, -1, 25));

        jButtonDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/clean.png"))); // NOI18N
        jButtonDeletar.setText("Deletar");
        jButtonDeletar.setMaximumSize(new java.awt.Dimension(90, 25));
        jButtonDeletar.setMinimumSize(new java.awt.Dimension(72, 25));
        jButtonDeletar.setPreferredSize(new java.awt.Dimension(90, 25));
        jButtonDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 90, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = jTableProdutos.getSelectedRow();
        
        if(linhaSelecionada == -1)
        {
            JOptionPane.showMessageDialog(this, "Nenhum produto Selecionado");
            return;
        }
        
        Object idObjeto = jTableProdutos.getValueAt(linhaSelecionada, 0);
        int id = (int) idObjeto;
        
        JDialogEditarProduto jDialogEditarProduto = new JDialogEditarProduto(null, true, id, jTableProdutos);
        jDialogEditarProduto.setVisible(true);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletarActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = jTableProdutos.getSelectedRow();
        
        if(linhaSelecionada == -1)
        {
            JOptionPane.showMessageDialog(this, "Nenhum produto Selecionado"); //depois verificar se tem selecionado e ativar o botao
            return;
        }

        int opcao = JOptionPane.showConfirmDialog(this, "Confirma a exclusão do produto?", "Excluir", JOptionPane.YES_NO_OPTION);
        
        if(opcao == JOptionPane.YES_OPTION)
        {
            ProdutoDAO produtoDAO = new ProdutoDAO();
            
            Object idObjeto = jTableProdutos.getValueAt(linhaSelecionada, 0);
            int id = (int) idObjeto;
            
            ProdutoModel produto = produtoDAO.obterProdutoPorID(id);
            
            produtoDAO.deletar(produto);
            JOptionPane.showMessageDialog(this, "Produto Excluído");    
            
            TableModelProduto tableModel = new TableModelProduto(produtoDAO.consultar());
            jTableProdutos.setModel(tableModel);
            
            //atualizarTamanhoTabela();
            ajustarTamanhoTabela();
        }
    }//GEN-LAST:event_jButtonDeletarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogGerenciarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogGerenciarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogGerenciarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogGerenciarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                JDialogGerenciarProduto dialog = new JDialogGerenciarProduto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() 
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) 
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeletar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable jTableProdutos;
    // End of variables declaration//GEN-END:variables
}
